### ISSUE TITLE
What does "Unknown or uninitialised column:" means?

### ISSUE THREAD

**Issue by PedroSapichu** [ropensci/microdemic#15]
Hi!

Thanks for this great package. Unfortunately, I don't use R very often, so I'm not sure what is the problem here. 

When I query a search for a paper abstract I get the following errors:

```
# A tibble: 0 x 1
# ... with 1 variable: abstract <chr>
Warning messages:
1: Unknown or uninitialised column: 'E'. 
2: Unknown or uninitialised column: 'Id'.
```

Is this a missing entry in Microsoft Academics, or do I need to "initialize" columns E + Id?

For instance, I get the error when I execute:

`ma_abstract(query = "Ti='Reversible gene knockdown in mice using a tight, inducible shRNA expression system'")`

Thanks!

**Comment by sckott** [comment]
please paste in the output of `sessionInfo()` after loading microdemic
