### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by VoIPshare** [ropensci/microdemic#21]
Hi
I always get error 500 when using the evaluate.
Am I the only one?

**Comment by poldham** [comment]
Hi, just to let you know that as mentioned in the other issue Microsoft academic closed on the 31st December 2021. So, the api is now dead. You may want to switch over to using OpenAlex at openalex.org which has a very nice api. I'm guessing that someone (hopefully with ropensci) will develop a package for open Alex and there may be info on the OpenAlex Twitter feed on that. Hope that helps.

**Comment by pbxip** [comment]
Thank you for the suggestion, I will look on it

**Comment by maelle** [comment]
this repository is about to be archived
